[general]
RemoteNickFormat="{NICK} ({CHANNEL}@{BRIDGE}): "
TranslationAttribution=" [translated by :google:]"
PreserveThreading=true
ShowUserTyping=true
MediaDownloadSize=1000000
ShowJoinPart=false
IconURL="https://identicons.github.com/{NICK}.png"

## ACCOUNTS

[slack]
[slack.swagfordev]
Token="${MATTERBRIDGE_SLACK_SWAGFORDEV_TOKEN}"
ShowJoinPart=false

[telegram]
[telegram.devswag]
Token="${MATTERBRIDGE_TELEGRAM_DEVSWAG_TOKEN}" # bot user: swagmatters_bot
RemoteNickFormat="{NICK}@{PROTOCOL}: "
UseInsecureURL=true
ShowJoinPart=false

[gitter]
[gitter.swagfordev]
Token="${MATTERBRIDGE_GITTER_SWAGFORDEV_TOKEN}"
ShowJoinPart=false

## GATEWAYS & BRIDGES

[[gateway]]
name="general"
enable=true
  [[gateway.inout]]
    account="slack.swagfordev"
    channel="general"
  [[gateway.inout]]
    account="telegram.devswag"
    channel="@devswag"
  [[gateway.inout]]
    account="gitter.swagfordev"
    channel="swag-for-dev/Lobby"
